GENERAL:
    BATCH_SIZE: 16
    NUM_WORKERS: 4
    DEVICE: 1
    SEED: 0
    EXTRACTOR: "CLIP"
    DATASET: "RefinedFashionIQ"
    TOP_K: [1, 5, 10, 25, 50]

RefinedFashionIQ:
    IMAGE_URL_FOLDER: '/data/data_fxu/RefinedFashionIQ/image_url'
    IMAGE_SIZE: 224
    OUTPUT_DIR: '/data/data_fxu/RefinedFashionIQ/downloaded_images'
    CAPTION_FOLDER: '/data/data_fxu/RefinedFashionIQ/captions'

CIRCO:
    IMAGE_FOLDER: '/data/data_fxu/CIRCO/image_url'
    IMAGE_SIZE: 224

CLIP:
    MODEL_NAME: "openai/clip-vit-base-patch32"
    IMAGE_SIZE: 224
    IMAGE_MEAN: [0.48145466, 0.4578275, 0.40821073]
    IMAGE_STD: [0.26862954, 0.26130258, 0.27577711]

BLIP2:
    MODEL_NAME: "Salesforce/blip2-itm-vit-g"
    IMAGE_SIZE: 224
    IMAGE_MEAN: [0.48145466, 0.4578275, 0.40821073]
    IMAGE_STD: [0.26862954, 0.26130258, 0.27577711]

BLIP2-OFFICIAL:
    MODEL_NAME: "blip2_feature_extractor"
    IMAGE_SIZE: 224
    IMAGE_MEAN: [0.48145466, 0.4578275, 0.40821073]
    IMAGE_STD: [0.26862954, 0.26130258, 0.27577711] 

SIGLIP2:
    MODEL_NAME: "google/siglip2-base-patch16-224"
    IMAGE_SIZE: 224
    IMAGE_MEAN: [0.5, 0.5, 0.5]
    IMAGE_STD: [0.5, 0.5, 0.5]

IMAGE-GENERATION:
    GLOBAL:
        NUM_INFERENCE_STEPS: 30
        IMAGE_GUIDANCE_SCALE: 1.1
        GUIDANCE_SCALE: 7.5
    SDXL-INSTRUCTPIX2PIX:
        MODEL_NAME: "diffusers/sdxl-instructpix2pix-768"
        IMAGE_SIZE: 768
        OUTPUT_DIR: '/data/data_fxu/FashionIQ/sdxl_instructpix2pix_output'
    SDXL-TURBO: # much faster than SDXL-INSTRUCTPIX2PIX
        MODEL_NAME: "stabilityai/sdxl-turbo"
        IMAGE_SIZE: 512
        OUTPUT_DIR: '/data/data_fxu/FashionIQ/sdxl_turbo_output'

TEXT-GENERATION:
    MODEL_NAME: "Qwen/Qwen2.5-VL-7B-Instruct"