General:
    BATCH_SIZE: 16
    TOP_K: 10
    NUM_WORKERS: 4
    DEVICE: 1

FashionIQ:
    IMAGE_URL_FOLDER: '/home/fxu/MultimodalQuery/CIR/fashion-iq/image_url'
    IMAGE_SIZE: 224
    OUTPUT_DIR: '/home/fxu/MultimodalQuery/CIR/fashion-iq/downloaded_images'
    CAPTION_FOLDER: '/home/fxu/MultimodalQuery/CIR/fashion-iq/captions'
